### PR TITLE
Update to tempo2 v2024.12.1

### PR DESCRIPTION
**Pull request by demorest**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Does what the title says!

### CODE REVIEW

**Comment by mattpitkin** [comment]
@conda-forge-admin, please rerender

**Comment by mattpitkin** [comment]
Just trying another re-render in case it fixes the osx build

**Comment by demorest** [comment]
Was just looking at this.  The OSX build is failing on `#include <string>`.  I think the CXXFLAGS are getting broken somehow.  conda claims this:
```
+CXXFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -fPIE -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/tempo2-2024.12.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
```
But tempo2 configure reports this:
```
configure: C++ compiler is x86_64-apple-darwin13.4.0-clang++ -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -fPIE -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/tempo2-2024.12.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -Wno-error -fopenmp -DHAVE_OPENMP
```
In particular the `-stdlib=libc++` is gone which is probably the issue.  Not sure why and/or what changed, but posting this info in case anyone else wants to pick it up.  If not I'll get back to it when possible..

**Comment by mattpitkin** [comment]
If this release is required for anything urgent, I'm happy for this to be merged with the osx build turned off, i.e., change:

```
skip: True  # [win]
```
to

```
skip: True  # [win or osx]
```

in the recipe. A new build could then be done later if/when we can fix the OSX issue.

**Comment by demorest** [comment]
OK thanks. I have one more fix to try.  If this doesn't work maybe we'll skip OSX for now.

**Pull request merged**
